// <auto-generated />
namespace Web_Selling_Laptop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixmodel4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixmodel4));
        
        string IMigrationMetadata.Id
        {
            get { return "202211140329114_fix-model4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
